# Generated by Django 5.0 on 2023-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('unitType', models.CharField(max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('carParking', models.IntegerField()),
                ('unitSize', models.IntegerField()),
                ('propertyPhoto', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
