# Generated by Django 5.0 on 2023-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='location',
            field=models.CharField(default='Dubai', max_length=50),
        ),
    ]
