# Generated by Django 5.0 on 2023-12-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_properties_propertiesdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertiesdetails',
            name='locationDetails',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='propertiesdetails',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
