# Generated by Django 5.0 on 2023-12-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertiesdetails_locationdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertiesdetails',
            name='locationDetails',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
