# Generated by Django 5.0 on 2023-12-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertiesdetails_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertiesdetails',
            name='project',
        ),
    ]
