# Generated by Django 5.0 on 2023-12-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_propertiesdetails_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertiesdetails',
            old_name='locationDetails',
            new_name='project',
        ),
    ]
