# Generated by Django 5.0 on 2023-12-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rename_locationdetails_propertiesdetails_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertiesdetails',
            old_name='propertyPhoto',
            new_name='propertyPhoto1',
        ),
        migrations.AddField(
            model_name='propertiesdetails',
            name='propertyPhoto2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='propertiesdetails',
            name='propertyPhoto3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='propertiesdetails',
            name='propertyPhoto4',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
